secrets:
  secret_key:
    file: ./secrets/secret_key
  redis_location:
    file: ./secrets/redis_location
services:
  web:
    build: ./web
    volumes:
      - ./web/db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles 
    expose:
      - 8000
    env_file:
      - ./.env
    secrets:
      - secret_key
      - redis_location
    depends_on:
      - redis
    environment:
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - REDIS_LOCATION_FILE=/run/secrets/redis_location
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - web
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  static_volume:
